### ISSUE TITLE
data process

### ISSUE THREAD

**Issue by techzz** [muyeby/AMR-Dialogue#1]
hi！i don‘t know how to preprocess the raw data and it is not included in this project. do you have the part of this code? Looking forward to your reply.

**Comment by muyeby** [comment]
Hi - Thank you for your interest in our paper.

Because constructing dialogue-level AMRs can be complex, including using several open-resource tools under different environments, which is difficult to be integrated into a script using one programming language under one environment, we did not release the codes. However, you can construct them following the below instructions:

1. Parse sentences into sentence-level AMRs, including pre-processing, parsing, and post-processing procedures: use [AMR-gs ](https://github.com/jcyk/AMR-gs) .
2. Add ``dummy`` node, and then add ``speaker`` edges between the dummy nodes and root nodes of each sentence-level AMRs: using any Python you like to process the AMR strings.
3. Align AMRs and tokens: we use [JAMR](https://github.com/jflanigan/jamr) .
4. Obtain coreference links within a dialogue: we use [neural-coref](https://github.com/huggingface/neuralcoref) on the dialogue text.
5. Simplify the AMR graphs obtained by Step 2, omitting the semantic tags of concept nodes: we use [AMR-simplifier](https://drive.google.com/u/0/uc?id=1PE8b44-H3Hu4I2Xf1XDAPFhH-GonR43i&export=download).
6. Add coreference edges (obtained by Step 3 and 4) and identical concept edges (by matching character strings. Note that pronouns should be not included.): using Python.
7. Feed the final AMRs obtained from step 6 into a graph neural network: please refer to [structural-transformer](https://github.com/Amazing-J/structural-transformer).

**Comment by Masamibai** [comment]
Hi - 
I think the accuracy of AMRs and coreference links is important in building the document-level graph. I wonder if the preprocess step(such as neural-coref tools) can correctly get the coref-relation? Especially for cross-sentence?
Looking forward your reply! Thanks.

**Comment by muyeby** [comment]
Hi, @Masamibai 

Thanks for your interest. According to our observation, the performance will drop when using a low-performance coreference tool. To control the quality of coreference links, we use the [neural-coref](https://github.com/huggingface/neuralcoref) tool with a low greedyness (0.3) .
